use crate::error::AppError;
use log::{debug, error, info};
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};

const NOTIFY_SCRIPT: &str = r#"#!/usr/bin/env bash
# Auto-generated by Branchdeck. Do not edit.
PORT="${BRANCHDECK_PORT:-13370}"
TAB_ID="${BRANCHDECK_TAB_ID:-}"
SESSION_ID="${BRANCHDECK_SESSION_ID:-}"
PAYLOAD=$(cat)
curl -s -X POST "http://127.0.0.1:${PORT}/hook" \
  -H "Content-Type: application/json" \
  -H "X-Branchdeck-Tab-Id: ${TAB_ID}" \
  -H "X-Branchdeck-Session-Id: ${SESSION_ID}" \
  -d "$PAYLOAD" --max-time 2 > /dev/null 2>&1 || true
"#;

const HOOK_EVENTS: &[&str] = &[
    "SessionStart",
    "PreToolUse",
    "PostToolUse",
    "SubagentStart",
    "SubagentStop",
    "Stop",
    "Notification",
];

/// Generates the `notify.sh` helper script in the Branchdeck config directory
/// and returns its absolute path.
///
/// # Errors
/// Returns `AppError` if the hooks directory cannot be created, the script cannot be written, or permissions fail.
pub fn ensure_notify_script() -> Result<PathBuf, AppError> {
    let hooks_dir = crate::services::config::config_dir()?.join("hooks");

    if !hooks_dir.exists() {
        std::fs::create_dir_all(&hooks_dir).map_err(|e| {
            error!(
                "Failed to create hooks directory {}: {e}",
                hooks_dir.display()
            );
            e
        })?;
    }

    let script_path = hooks_dir.join("notify.sh");
    std::fs::write(&script_path, NOTIFY_SCRIPT).map_err(|e| {
        error!(
            "Failed to write notify script {}: {e}",
            script_path.display()
        );
        e
    })?;

    let mut perms = std::fs::metadata(&script_path)?.permissions();
    perms.set_mode(0o755);
    std::fs::set_permissions(&script_path, perms).map_err(|e| {
        error!(
            "Failed to set permissions on {}: {e}",
            script_path.display()
        );
        e
    })?;

    let resolved = script_path.canonicalize().map_err(|e| {
        error!("Failed to resolve notify script path: {e}");
        e
    })?;

    info!("Ensured notify script at {}", resolved.display());
    Ok(resolved)
}

/// Installs hooks at user level (`~/.claude/settings.json`).
/// Works for all repos and worktrees.
///
/// # Errors
/// Returns `AppError` if the settings file cannot be read, parsed, or written.
pub fn install_hooks_user_level(script_path: &Path) -> Result<(), AppError> {
    let home = dirs::home_dir()
        .ok_or_else(|| AppError::Agent("Could not determine home directory".to_string()))?;
    let claude_dir = home.join(".claude");
    if !claude_dir.exists() {
        std::fs::create_dir_all(&claude_dir).map_err(|e| {
            error!("Failed to create ~/.claude dir: {e}");
            e
        })?;
    }
    let settings_path = claude_dir.join("settings.json");
    install_hooks_at(&settings_path, script_path)?;
    info!("Installed hooks at user level");
    Ok(())
}

/// Removes hooks from user level (`~/.claude/settings.json`).
///
/// # Errors
/// Returns `AppError` if the settings file cannot be read, parsed, or written.
pub fn remove_hooks_user_level(script_path: &Path) -> Result<(), AppError> {
    let home = dirs::home_dir()
        .ok_or_else(|| AppError::Agent("Could not determine home directory".to_string()))?;
    let settings_path = home.join(".claude").join("settings.json");
    remove_hooks_at(&settings_path, script_path)?;
    info!("Removed hooks from user level");
    Ok(())
}

/// Installs hooks at project level (`{repo}/.claude/settings.json`).
///
/// # Errors
/// Returns `AppError` if the settings file cannot be created, read, or written.
pub fn install_hooks(repo_path: &str, script_path: &Path) -> Result<(), AppError> {
    let claude_dir = Path::new(repo_path).join(".claude");
    if !claude_dir.exists() {
        std::fs::create_dir_all(&claude_dir).map_err(|e| {
            error!("Failed to create .claude dir in {repo_path:?}: {e}");
            e
        })?;
    }
    let settings_path = claude_dir.join("settings.json");
    install_hooks_at(&settings_path, script_path)?;
    info!("Installed hooks in {repo_path:?}");
    Ok(())
}

/// Removes hooks from project level (`{repo}/.claude/settings.json`).
///
/// # Errors
/// Returns `AppError` if the settings file cannot be read, parsed, or written.
pub fn remove_hooks(repo_path: &str, script_path: &Path) -> Result<(), AppError> {
    let settings_path = Path::new(repo_path).join(".claude").join("settings.json");
    remove_hooks_at(&settings_path, script_path)?;
    info!("Removed hooks from {repo_path:?}");
    Ok(())
}

// --- Shared helpers ---

fn install_hooks_at(settings_path: &Path, script_path: &Path) -> Result<(), AppError> {
    let mut settings = load_settings(settings_path)?;

    let script_cmd = script_path.to_string_lossy().to_string();
    // Claude Code hook format: {"matcher": "", "hooks": [{"type": "command", "command": "..."}]}
    // Empty matcher matches all tools/events
    let matcher_entry = serde_json::json!({
        "matcher": "",
        "hooks": [{"type": "command", "command": script_cmd}]
    });

    let hooks = settings
        .as_object_mut()
        .ok_or_else(|| AppError::Agent("settings.json root is not an object".to_string()))?
        .entry("hooks")
        .or_insert_with(|| serde_json::json!({}));

    let hooks_obj = hooks
        .as_object_mut()
        .ok_or_else(|| AppError::Agent("hooks key is not an object".to_string()))?;

    for event in HOOK_EVENTS {
        let arr = hooks_obj
            .entry(*event)
            .or_insert_with(|| serde_json::json!([]));

        let entries = arr
            .as_array_mut()
            .ok_or_else(|| AppError::Agent(format!("hooks.{event} is not an array")))?;

        let already_present = entries.iter().any(|entry| {
            entry
                .get("hooks")
                .and_then(serde_json::Value::as_array)
                .is_some_and(|hooks| {
                    hooks.iter().any(|h| {
                        h.get("command").and_then(serde_json::Value::as_str) == Some(&script_cmd)
                    })
                })
        });

        if !already_present {
            entries.push(matcher_entry.clone());
        }
    }

    atomic_write_json(settings_path, &settings)
}

fn remove_hooks_at(settings_path: &Path, script_path: &Path) -> Result<(), AppError> {
    if !settings_path.exists() {
        debug!(
            "No settings at {}, nothing to remove",
            settings_path.display()
        );
        return Ok(());
    }

    let mut settings = load_settings(settings_path)?;
    let script_cmd = script_path.to_string_lossy().to_string();

    let root = settings
        .as_object_mut()
        .ok_or_else(|| AppError::Agent("settings.json root is not an object".to_string()))?;

    if let Some(hooks) = root
        .get_mut("hooks")
        .and_then(serde_json::Value::as_object_mut)
    {
        let mut empty_events = Vec::new();

        for event in HOOK_EVENTS {
            if let Some(arr) = hooks
                .get_mut(*event)
                .and_then(serde_json::Value::as_array_mut)
            {
                arr.retain(|entry| {
                    // Check new format: {"matcher": "", "hooks": [{"command": "..."}]}
                    let is_ours = entry
                        .get("hooks")
                        .and_then(serde_json::Value::as_array)
                        .is_some_and(|hooks| {
                            hooks.iter().any(|h| {
                                h.get("command").and_then(serde_json::Value::as_str)
                                    == Some(&script_cmd)
                            })
                        });
                    !is_ours
                });
                if arr.is_empty() {
                    empty_events.push((*event).to_string());
                }
            }
        }

        for event in &empty_events {
            hooks.remove(event);
        }

        if hooks.is_empty() {
            root.remove("hooks");
        }
    }

    // Don't delete user-level settings.json even if hooks section is now empty
    // (it may contain other settings like env, permissions, etc.)
    atomic_write_json(settings_path, &settings)
}

fn load_settings(path: &Path) -> Result<serde_json::Value, AppError> {
    if !path.exists() {
        return Ok(serde_json::json!({}));
    }

    let contents = std::fs::read_to_string(path).map_err(|e| {
        error!("Failed to read {}: {e}", path.display());
        e
    })?;

    serde_json::from_str(&contents).map_err(|e| {
        error!("Failed to parse {}: {e}", path.display());
        AppError::Agent(format!("Invalid JSON in {}: {e}", path.display()))
    })
}

fn atomic_write_json(path: &Path, value: &serde_json::Value) -> Result<(), AppError> {
    let tmp_path = path.with_extension("json.tmp");
    let contents = serde_json::to_string_pretty(value).map_err(|e| {
        error!("Failed to serialize settings JSON: {e}");
        AppError::Agent(e.to_string())
    })?;

    std::fs::write(&tmp_path, contents).map_err(|e| {
        error!("Failed to write {}: {e}", tmp_path.display());
        e
    })?;

    std::fs::rename(&tmp_path, path).map_err(|e| {
        error!(
            "Failed to rename {} -> {}: {e}",
            tmp_path.display(),
            path.display()
        );
        e
    })?;

    debug!("Atomic write to {}", path.display());
    Ok(())
}
