use crate::error::AppError;
use log::{debug, error, info};
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};

const NOTIFY_SCRIPT: &str = r#"#!/usr/bin/env bash
# Auto-generated by Branchdeck. Do not edit.
PORT="${BRANCHDECK_PORT:-13370}"
TAB_ID="${BRANCHDECK_TAB_ID:-}"
SESSION_ID="${BRANCHDECK_SESSION_ID:-}"
PAYLOAD=$(cat)
# Inject routing context by replacing the closing } with additional fields
BODY="${PAYLOAD%\}},\"branchdeck_tab_id\":\"${TAB_ID}\",\"branchdeck_session_id\":\"${SESSION_ID}\"}"
curl -s -X POST "http://127.0.0.1:${PORT}/hook" \
  -H "Content-Type: application/json" \
  -d "$BODY" --max-time 2 > /dev/null 2>&1 || true
"#;

const HOOK_EVENTS: &[&str] = &[
    "SessionStart",
    "PreToolUse",
    "PostToolUse",
    "SubagentStart",
    "SubagentStop",
    "Stop",
    "Notification",
];

/// Generates the `notify.sh` helper script in the Branchdeck config directory
/// and returns its absolute path. The script is always overwritten so that
/// upgrades pick up any template changes.
pub fn ensure_notify_script() -> Result<PathBuf, AppError> {
    let hooks_dir = crate::services::config::config_dir()?.join("hooks");

    if !hooks_dir.exists() {
        std::fs::create_dir_all(&hooks_dir).map_err(|e| {
            error!(
                "Failed to create hooks directory {}: {e}",
                hooks_dir.display()
            );
            e
        })?;
    }

    let script_path = hooks_dir.join("notify.sh");
    std::fs::write(&script_path, NOTIFY_SCRIPT).map_err(|e| {
        error!(
            "Failed to write notify script {}: {e}",
            script_path.display()
        );
        e
    })?;

    let mut perms = std::fs::metadata(&script_path)?.permissions();
    perms.set_mode(0o755);
    std::fs::set_permissions(&script_path, perms).map_err(|e| {
        error!(
            "Failed to set permissions on {}: {e}",
            script_path.display()
        );
        e
    })?;

    let resolved = script_path.canonicalize().map_err(|e| {
        error!("Failed to resolve notify script path: {e}");
        e
    })?;

    info!("Ensured notify script at {}", resolved.display());
    Ok(resolved)
}

/// Merges Branchdeck hook entries into `{repo_path}/.claude/settings.json`.
/// Preserves any existing user hooks. Uses atomic writes.
pub fn install_hooks(repo_path: &str, script_path: &Path) -> Result<(), AppError> {
    let claude_dir = Path::new(repo_path).join(".claude");
    if !claude_dir.exists() {
        std::fs::create_dir_all(&claude_dir).map_err(|e| {
            error!("Failed to create .claude dir in {repo_path:?}: {e}");
            e
        })?;
    }

    let settings_path = claude_dir.join("settings.json");
    let mut settings = load_settings(&settings_path)?;

    let script_cmd = script_path.to_string_lossy().to_string();
    let hook_entry = serde_json::json!({"type": "command", "command": script_cmd});

    let hooks = settings
        .as_object_mut()
        .ok_or_else(|| AppError::Agent("settings.json root is not an object".to_string()))?
        .entry("hooks")
        .or_insert_with(|| serde_json::json!({}));

    let hooks_obj = hooks
        .as_object_mut()
        .ok_or_else(|| AppError::Agent("hooks key is not an object".to_string()))?;

    for event in HOOK_EVENTS {
        let arr = hooks_obj
            .entry(*event)
            .or_insert_with(|| serde_json::json!([]));

        let entries = arr
            .as_array_mut()
            .ok_or_else(|| AppError::Agent(format!("hooks.{event} is not an array")))?;

        let already_present = entries.iter().any(|entry| {
            entry.get("command").and_then(serde_json::Value::as_str) == Some(&script_cmd)
        });

        if !already_present {
            entries.push(hook_entry.clone());
        }
    }

    atomic_write_json(&settings_path, &settings)?;
    info!("Installed hooks in {repo_path:?}");
    Ok(())
}

/// Removes Branchdeck hook entries from `{repo_path}/.claude/settings.json`.
/// Keeps user hooks intact. Uses atomic writes. Cleans up empty structures.
pub fn remove_hooks(repo_path: &str, script_path: &Path) -> Result<(), AppError> {
    let settings_path = Path::new(repo_path).join(".claude").join("settings.json");

    if !settings_path.exists() {
        debug!("No settings.json in {repo_path:?}, nothing to remove");
        return Ok(());
    }

    let mut settings = load_settings(&settings_path)?;
    let script_cmd = script_path.to_string_lossy().to_string();

    let root = settings
        .as_object_mut()
        .ok_or_else(|| AppError::Agent("settings.json root is not an object".to_string()))?;

    if let Some(hooks) = root
        .get_mut("hooks")
        .and_then(serde_json::Value::as_object_mut)
    {
        let mut empty_events = Vec::new();

        for event in HOOK_EVENTS {
            if let Some(arr) = hooks
                .get_mut(*event)
                .and_then(serde_json::Value::as_array_mut)
            {
                arr.retain(|entry| {
                    entry.get("command").and_then(serde_json::Value::as_str) != Some(&script_cmd)
                });
                if arr.is_empty() {
                    empty_events.push((*event).to_string());
                }
            }
        }

        for event in &empty_events {
            hooks.remove(event);
        }

        if hooks.is_empty() {
            root.remove("hooks");
        }
    }

    // If the entire settings object is empty, delete the file
    if root.is_empty() {
        std::fs::remove_file(&settings_path).map_err(|e| {
            error!("Failed to delete empty settings.json in {repo_path:?}: {e}");
            e
        })?;
        info!("Removed empty settings.json from {repo_path:?}");
    } else {
        atomic_write_json(&settings_path, &settings)?;
        info!("Removed hooks from {repo_path:?}");
    }

    Ok(())
}

/// Loads settings.json, returning an empty object if the file doesn't exist.
fn load_settings(path: &Path) -> Result<serde_json::Value, AppError> {
    if !path.exists() {
        return Ok(serde_json::json!({}));
    }

    let contents = std::fs::read_to_string(path).map_err(|e| {
        error!("Failed to read {}: {e}", path.display());
        e
    })?;

    serde_json::from_str(&contents).map_err(|e| {
        error!("Failed to parse {}: {e}", path.display());
        AppError::Agent(format!("Invalid JSON in {}: {e}", path.display()))
    })
}

/// Writes JSON to a file atomically (write tmp, then rename).
fn atomic_write_json(path: &Path, value: &serde_json::Value) -> Result<(), AppError> {
    let tmp_path = path.with_extension("json.tmp");
    let contents = serde_json::to_string_pretty(value).map_err(|e| {
        error!("Failed to serialize settings JSON: {e}");
        AppError::Agent(e.to_string())
    })?;

    std::fs::write(&tmp_path, contents).map_err(|e| {
        error!("Failed to write {}: {e}", tmp_path.display());
        e
    })?;

    std::fs::rename(&tmp_path, path).map_err(|e| {
        error!(
            "Failed to rename {} -> {}: {e}",
            tmp_path.display(),
            path.display()
        );
        e
    })?;

    debug!("Atomic write to {}", path.display());
    Ok(())
}
